apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: ""
  namespace: ""
spec:
  parallelism: 1
  script:
    configMap:
      name: k6-test-script
      file: script.js
  runner:
    image: grafana/k6:latest
    env:
      - name: KEYCLOAK_CLIENT_ID
        value: ""
      - name: KEYCLOAK_CLIENT_SECRET
        value: ""
      - name: KEYCLOAK_ISSUER
        value: ""
      - name: BASE_URL
        value: ""
      - name: TEST_CPF
        value: ""
      - name: TEST_SCENARIO
        value: ""
      - name: DURATION
        value: ""
      - name: VIRTUAL_USERS
        value: ""
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 200m
        memory: 512Mi
